# Generated by Django 4.2.1 on 2023-05-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pH', models.FloatField()),
                ('Hardness', models.FloatField()),
                ('Solids', models.FloatField()),
                ('Chloramines', models.FloatField()),
                ('Sulfate', models.FloatField()),
                ('Conductivity', models.FloatField()),
                ('Organic_carbon', models.FloatField()),
                ('Trihalomethanes', models.FloatField()),
                ('Turbidity', models.FloatField()),
            ],
        ),
    ]
